# Generated by Django 4.0 on 2022-02-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_alter_userprofilephoto_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.TextField(max_length=1000)),
                ('video_desc', models.TextField(max_length=5000)),
                ('video_likes', models.IntegerField(default=0)),
                ('video_views', models.IntegerField(default=0)),
                ('video_file', models.FileField(upload_to='videoFiles')),
                ('notes_file', models.FileField(null=True, upload_to='notesFiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
