# Generated by Django 4.0 on 2022-02-28 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_videodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
