# Generated by Django 4.0 on 2022-02-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_videodata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='video_report_count',
            field=models.IntegerField(default=0),
        ),
    ]
