# Generated by Django 4.0 on 2022-03-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_videodata_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='video_keywords',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
