# Generated by Django 4.0 on 2022-03-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_videodata_video_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='video_desc',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='video_keywords',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='video_title',
            field=models.CharField(max_length=1000),
        ),
    ]
