# Generated by Django 4.0 on 2022-04-09 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0015_loginstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('roomName', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=4000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
