# Generated by Django 4.0 on 2022-04-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chatroom_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.AddField(
            model_name='messages',
            name='username',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='room',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
