# Generated by Django 4.0 on 2022-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_messages_user_messages_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='roomPass',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
