# Generated by Django 4.0 on 2022-04-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_videodata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='video_uploader_img',
            field=models.ImageField(blank=True, null=True, upload_to='channelPhotos'),
        ),
    ]
