# Generated by Django 4.0 on 2022-05-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_quicknotes_notes_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicknotes',
            name='video_id',
        ),
    ]
