# Generated by Django 4.0 on 2022-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_reportedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
