# Generated by Django 4.0 on 2022-05-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0027_videodata_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='phone',
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
