# Generated by Django 4.0 on 2022-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_videodata_phone_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicknotes',
            name='video_id',
            field=models.IntegerField(default=1),
        ),
    ]
